# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
workflows:
  version: 2
  test:
    jobs:
      - lint
      - pyre
      - test-3.7
      - test-3.6

tox_command: &tox_command
  steps:
    - checkout
    - run:
        name: install tox
        command: pip install --user tox
    - run:
        name: run tox
        command: ~/.local/bin/tox

jobs:
  lint:
    <<: *tox_command
    docker:
      - image: circleci/python:3.7
        environment:
          TOXENV: lint
  pyre:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: run pyre
          command: |
            python3 -m venv /tmp/libcst-env/
            source /tmp/libcst-env/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt -r requirements-dev.txt
            pyre check

  test-3.7:
    <<: *tox_command
    docker:
      - image: circleci/python:3.7
        environment:
          TOXENV: py37

  test-3.6:
    <<: *tox_command
    docker:
      - image: circleci/python:3.6
        environment:
          TOXENV: py36
